### ISSUE TITLE
Replace building open_time and close_time with schedules?

### ISSUE THREAD

**Issue by mkarpman** [open229/ruleset-model-report-schema#12]
Suggest to replaced open_time and close_time with hourly schedules as these may vary by day of the week and seasons (e.g. for a school). Or maybe remove it altogether? This is a useful info, but not something that is captured in the model outside of the operating schedules assigned to particular component - e.g. occupancy or HVAC.

**Comment by JasonGlazer** [comment]
This specifically for the exterior lighting related to when the building opens and closes to confirm the following:

![image](https://user-images.githubusercontent.com/2582150/125823980-af696b0d-7e58-465c-ab0c-633a64a538e5.png)


It is difficult to infer when a building is open or closed based on occupancy or HVAC schedule. I will add a schedule reference here instead of open_time and close_time.

**Comment by mkarpman** [comment]
I see, sounds good. Thanks!



*From:* Jason Glazer ***@***.***>
*Sent:* Thursday, July 15, 2021 12:36 PM
*To:* open229/ruleset-model-report-schema <
***@***.***>
*Cc:* mkarpman ***@***.***>; Author <
***@***.***>
*Subject:* Re: [open229/ruleset-model-report-schema] Replace building
open_time and close_time with schedules? (#12)



This specifically for the exterior lighting related to when the building
opens and closes to confirm the following:

[image: image]
<https://user-images.githubusercontent.com/2582150/125823980-af696b0d-7e58-465c-ab0c-633a64a538e5.png>

It is difficult to infer when a building is open or closed based on
occupancy or HVAC schedule. I will add a schedule reference here instead of
open_time and close_time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/open229/ruleset-model-report-schema/issues/12#issuecomment-880846374>,
or unsubscribe
