### ISSUE TITLE
Retail additional lighting power allowance

### ISSUE THREAD

**Issue by supriyagoel** [open229/ruleset-model-report-schema#23]
90.1 Addendum AF adds a requirement for additional lighting power in the baseline, if the same has been modeled for the proposed. 
Where retail display lighting is included in the proposed building design in accordance with Section 9.6.2(b), the baseline building design retail display lighting additional power shall be equal to the limits established by Section 9.6.2(b) or same as proposed, which ever less.

BEM tools are unlikely to include an input for 'additional retail lighting power' for the proposed building. Should a data element still be included? We would then have a rule which will likely not be evaluated and have a 'CAUTION' outcome for manual verification.
@JasonGlazer @mkarpman @mcneillj

**Comment by mkarpman** [comment]
I don't think this should be a separate RDS for the reasons that you described. Instead, I would just capture it in the RDS that verifies the baseline LPD. So if space type = Sales Area AND baseline LPD is not as expected, RCT would flag it as caution instead of error with a message saying that it is an error unless proposed design has additional retail lighting power meeting requirements of the exception. Reviewer can then manually check for that. As a side not, this rule is not in 90.1 2019, so why are we looking into this?

**Comment by supriyagoel** [comment]
@mkarpman that makes sense. I can add this comment to RDS 6-8.
regarding this rule not being in 90.1-2019, we have been trying to incorporate addenda that are clarifications to 2019 and don't add new requirements. I believe AF falls under the same category. Let me know what you think.

**Comment by mkarpman** [comment]
I believe AF is a change in rules and not a clarification. In 90.1 2019 "Interior lighting power in the baseline building design shall be determined using the values in Table G3.7." There are no additional allowances. Addendum AF added retail lighting allowance (but not decorative lighting allowance), making the requirements less stringent. While retail lighting allowance may have been ommitted  unintentionally, it was excluded nevertheless.
